[platformio]
default_envs = uno_r4_unified

[env]
platform = renesas-ra@1.8.0
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_compat_mode = off
lib_deps =
  https://github.com/felis/USB_Host_Shield_2.0.git#1.7.0
  arduino-libraries/ArduinoMDNS@1.0.1
build_flags = -Iinclude
extra_scripts = pre:scripts/patch_usb_host.py

[env:uno_r4_acm]
build_flags = ${env.build_flags} -DBRIDGE_DRIVER=1

[env:uno_r4_unified]
build_flags = ${env.build_flags} -DBRIDGE_DRIVER=5

[env:uno_r4_ftdi]
build_flags = ${env.build_flags} -DBRIDGE_DRIVER=2

[env:uno_r4_pl2303]
build_flags = ${env.build_flags} -DBRIDGE_DRIVER=3

[env:uno_r4_printer]
build_flags = ${env.build_flags} -DBRIDGE_DRIVER=4
